// models/PushSubscription.js

import mongoose from 'mongoose';

const pushSubscriptionSchema = new mongoose.Schema({
  user: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true
  },
  // The subscription object from the browser
  endpoint: {
    type: String,
    required: true,
    unique: true
  },
  // Encryption keys for secure push messages
  keys: {
    p256dh: {
      type: String,
      required: true
    },
    auth: {
      type: String,
      required: true
    }
  },
  // Track which device/browser this is from
  userAgent: String,
  // When subscription was created
  createdAt: {
    type: Date,
    default: Date.now
  },
  // Track if subscription is still valid
  isActive: {
    type: Boolean,
    default: true
  }
}, {
  timestamps: true
});

// Index for faster queries
pushSubscriptionSchema.index({ user: 1, isActive: 1 });

export default mongoose.model('PushSubscription', pushSubscriptionSchema);

// WHY THIS MODEL?
// - endpoint: Unique URL for each browser subscription (where to send notifications)
// - keys.p256dh & keys.auth: Encryption keys generated by the browser
// - userAgent: Helps identify which device (user might have multiple)
// - isActive: Mark subscriptions as inactive if they fail (expired/unsubscribed)